<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5Lqn5ZOB5pyN5Yqh');
$cfg_Cs[2]=array(0,1,1,'5qGI5L6L5bGV56S6');
$cfg_Cs[3]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[4]=array(0,1,1,'5Zyo57q/55Sz6K+3');
$cfg_Cs[5]=array(2,1,1,'5a6Y5pa5572R56uZ');
$cfg_Cs[6]=array(2,1,1,'6Zeo5oi3572R56uZ');
$cfg_Cs[7]=array(2,1,1,'56e75Yqo5bqU55So');
$cfg_Cs[8]=array(2,1,1,'5Lqk5LqS6aG16Z2i');
$cfg_Cs[9]=array(2,1,1,'55S15ZWG5bmz5Y+w');
?>