<div class="cell_wrap cell_wrap_case">
            <div class="cell_wrap_b">
                <div class="cell_wrap_container">
                    <a class="case_img" href="[field:arcurl/]">
                        <img src="[field:picname/]" />
                    </a>
                </div>
                <div class="cf case_txt">
                    <a href="[field:arcurl/]" class="f_left">[field:title/]</a>
                    <span class="f_right">[field:typelink/]</span>
                </div>
            </div>
            <div class="after"></div>
        </div>