<div class="cell_wrap cell_team">
            <a href="[field:arcurl/]" target="_blank">
            <div class="cell_wrap_b">
                <div class="cell_wrap_container">
                    <span class="teme_img">
                        <img width="300" height="300" src="[field:picname/]">
                    </span>
                </div>
                <div class="cf team_txt">
                    <p class="team_title">[field:title/]</p>
                    <p class="team_intro">[field:description function='cn_substr(Html2text("@me"),160)'/]</p>
                    <p class="team_intro"><b>QQ：</b>[field:qq/]</p>
                    <p class="team_intro"><b>Blog：</b><a target="_blank" href="[field:boke/]">[field:boke/]</a></p>
                </div>
            </div>
            </a>
        </div>