<?php
$z[0]=Array("global","",55,82);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",123,150);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("type","\r\n            <a href=\"[field:typelink /]\" class=\"icon_nav icon_nav_1\">\r\n                <span class=\"gaoguang\"></span>\r\n                <img src=\"[field:global.cfg_basehost/]/style/images/icon_1.png\" width=\"95\" height=\"145\" />\r\n            </a>\r\n            <a href=\"[field:typelink /]\" class=\"nav_txt\">[field:typename /]</a>\r\n            <div class=\"choose_1\"></div>\r\n            ",320,736);
$z[2][4]['typeid']="1";
$z[3]=Array("type","\r\n            <span class=\"gaoguang\"></span>\r\n            <a href=\"[field:typelink /]\" class=\"icon_nav icon_nav_2\">\r\n                <img src=\"[field:global.cfg_basehost/]/style/images/icon_2.png\" width=\"70\" height=\"126\" />\r\n            </a>\r\n            <a href=\"[field:typelink /]\" class=\"nav_txt\">[field:typename /]</a>\r\n            <div class=\"choose_2\"></div>\r\n            ",797,1209);
$z[3][4]['typeid']="2";
$z[4]=Array("type","\r\n            <span class=\"gaoguang\"></span>\r\n            <a href=\"[field:typelink /]\" class=\"icon_nav icon_nav_3\">\r\n                <img src=\"[field:global.cfg_basehost/]/style/images/icon_3.png\" width=\"81\" height=\"100\" />\r\n            </a>\r\n            <a href=\"[field:typelink /]\" class=\"nav_txt\">[field:typename /]</a>\r\n            <div class=\"choose_3\"></div>\r\n            ",1270,1682);
$z[4][4]['typeid']="3";
$z[5]=Array("type","\r\n            <span class=\"gaoguang\"></span>\r\n            <a href=\"[field:typelink /]\" class=\"icon_nav icon_nav_4\">\r\n                <img src=\"[field:global.cfg_basehost/]/style/images/icon_4.png\" width=\"89\" height=\"89\" />\r\n            </a>\r\n            <a href=\"[field:typelink /]\" class=\"nav_txt\">[field:typename /]</a>\r\n            <div class=\"choose_4\"></div>\r\n            ",1743,2154);
$z[5][4]['typeid']="4";
$z[6]=Array("type","[field:ID /]",2215,2250);
$z[7]=Array("global","",2344,2371);
$z[7][4]['name']="cfg_basehost";

?>